#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
image:
    - Visual Studio 2017
    - Visual Studio 2015
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: |
        Get-ComputerInfo -Verbose
        $moduleName = 'xPSDesiredStateConfiguration'
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

# build: false
build_script:
  - docker pull microsoft/nanoserver

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -DisableConsistency

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
        Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName
