#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
image:
    - Visual Studio 2017
install:
    - docker images
    - docker run -d -p 80 --name testnanoserver microsoft/nanoserver
    - docker ps -a
    - docker cp C:\projects\xpsdesiredstateconfiguration\. testnanoserver:/Install
    - docker start -i testnanoserver
    - docker run testnanoserver powershell -noprofile -command "get-computerInfo -verbose"
    #- docker start -i TestNanoServer
    - docker exec -i -t TestNanoServer git clone https://github.com/PowerShell/DscResource.Tests
    - docker exec -i -t TestNanoServer PowerShell
    - docker exec -i -t TestNanoServer Get-ComputerInfo -Verbose
    - docker exec -i -t TestNanoServer $moduleName = 'xPSDesiredStateConfiguration'
    - docker exec -i -t TestNanoServer Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - docker exec -i -t TestNanoServer Invoke-AppveyorInstallTask
    - docker stop TestNanoServer

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false
# build_script:
  

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -DisableConsistency

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
        Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName
