#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
image:
    - Visual Studio 2017
install:
    - docker images
    - docker create -t --name TestNanoServer -h NanoServer -i microsoft/nanoserver
    - docker start -i TestNanoServer
    - docker git clone https://github.com/PowerShell/DscResource.Tests
    - docker PowerShell
    - docker Get-ComputerInfo -Verbose
    - ps: |
        $moduleName = 'xPSDesiredStateConfiguration'
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask
    - docker stop TestNanoServer

#---------------------------------#
#      build configuration        #
#---------------------------------#

# build: false
build_script:
  - docker pull microsoft/nanoserver

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -DisableConsistency

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
        Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName
