#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
environment:
  gallery_api:
    secure: 9ekJzfsPCDBkyLrfmov83XbbhZ6E2N3z+B/Io8NbDetbHc6hWS19zsDmy7t0Vvxv

image:
- Visual Studio 2015
- Visual Studio 2017

configuration:
- Meta
- Unit
- Integration

matrix:
  exclude:
    - configuration: Meta
      image: Visual Studio 2017

install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: |
        $moduleName = 'xPSDesiredStateConfiguration'
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

for:
-
  matrix:
    only:
      - configuration: Meta

  test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -ExcludeTag @()

-
  matrix:
    only:
      - configuration: Integration
  environment:
    SkipAllCommonTests: True

  test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -DisableConsistency `
            -ExcludeTag @()

-
  matrix:
    only:
      - configuration: Unit
  environment:
    SkipAllCommonTests: True

  test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -ExcludeTag @()

after_test:
- ps: |
    Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    Invoke-AppveyorAfterTestTask `
        -ResourceModuleName $moduleName

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - ps: |
        Invoke-AppVeyorDeployTask
